### ISSUE TITLE
qr code not popping up

### ISSUE THREAD

**Issue by mailustoday** [Its-Traadev/Fake-Verification-QR-Discord#4]
Discord bot works fine but when you press the verify button everything pops up besides the QR code

**Comment by Its-Traadev** [comment]
Fixed

**Comment by mailustoday** [comment]
The problem is still **on-going**

``I've enabled all intents``
``installed every module``
message me on discord , mail#0001

<img width="641" alt="image" src="https://user-images.githubusercontent.com/116463050/197692411-516390e3-3d3a-4d76-a8ac-e798bf2b67bf.png">

**Comment by mailustoday** [comment]
this is the error I'm getting

```Task exception was never retrieved
future: <Task finished name='Task-22' coro=<start.<locals>.verification_callback.<locals>.RemoteAuthClient.run() done, defined at main.py:169> exception=AttributeError("'NoneType' object has no attribute 'cancel'")>
Traceback (most recent call last):
  File "main.py", line 214, in run
    self._heartbeatTask.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'

**Comment by Its-Traadev** [comment]
are you on windows 11 os ?

**Comment by mailustoday** [comment]
I'm running it on replit , I'm currently on Mac OS
